# Generated by Django 4.1 on 2023-08-17 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_name", models.CharField(blank=True, max_length=100)),
                ("file", models.FileField(upload_to="attachments")),
                ("file1", models.FileField(default="", upload_to="attachments1")),
                ("file2", models.FileField(default="", upload_to="attachments2")),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sub_Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Clothe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clothe_name", models.CharField(blank=True, max_length=50)),
                (
                    "sleeve",
                    models.CharField(
                        choices=[("full", "full"), ("half", "half"), ("less", "less")],
                        default="full",
                        max_length=5,
                    ),
                ),
                (
                    "lenth",
                    models.CharField(
                        choices=[("full", "full"), ("half", "half")],
                        default="full",
                        max_length=5,
                    ),
                ),
                (
                    "ckpt",
                    models.CharField(
                        choices=[("0", "0"), ("1", "1")], default="0", max_length=5
                    ),
                ),
                ("clothes_orginal", models.FileField(upload_to="clothes_orginal")),
                ("clothes", models.FileField(upload_to="clothes")),
                ("clothes_mask", models.FileField(upload_to="clothes_mask")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.category",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.sub_category",
                    ),
                ),
            ],
        ),
    ]
