# Generated by Django 2.2.10 on 2023-08-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file1',
            field=models.FileField(default='', upload_to='attachments1'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file2',
            field=models.FileField(default='', upload_to='attachments2'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='image_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
