# Generated by Django 3.2.12 on 2023-08-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20230824_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
    ]
