# Generated by Django 3.2.12 on 2023-08-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_clothe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='sub_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.sub_category'),
        ),
    ]
